from .regist_meta_arch import META_ARCH_REGISTRY
from .mtnet import MultiTaskNet
from .pcgrad_net import PCGradNet
from .mgda_net import MGDANet
from .cosreg_net import CosRegNet
from .vanden import VandenNet
from .mtan import MTANet
from .mtinet import MTINetwork
from .auto_lambda import AutoLambda
from .augment_autol import AugAutoLambda
